トークン生成APIのテストを作成
sls-training/2023-rails-sample pull request #13
Opened 2023-05-08 05:20 UTC by Taku3939

## やったこと
- APIのテストを作成
- jwtの検証をするテストを作成

###  spec/requests/api/token_spec.rbに次の3通りのテストを作成した。
- '正しいログイン情報の場合'  : 200でアクセストークンがレスポンスとして返ってくる
- '正しいログイン情報だが、Adminでない場合' : 403で'Access denied. You are not admin user'というメッセージが入っている
- '不明なログイン情報の場合' : 401で'Unauthorized. Make sure you have the parameters.'というメッセージが入っている

### spec/utils/token_util_spec.rbにtokenを検証するためのテストを作成した
jwtエンコードしたものをデコードし直して次の2点を検証した
- payloadに正しいemailとexpが入っているか
- headerのalgは`HS256`になっているか

2023-05-08 07:07 UTC, KT-tim commented
うちのチームでは実装のif文の構造に合わせてspecのcontextを書くことになっているから、こういう感じになるね
```
context "ユーザーが存在する場合" do
  context "ユーザーがadminではない場合" do
  end
  context "ユーザーがadminの場合" do
  end
  context "パスワードが間違っている場合" do
  end
end

context "ユーザーが存在しない場合" do
end
```

2023-05-08 07:25 UTC, KT-tim requested changes

2023-05-08 07:25 UTC, KT-tim commented on spec/requests/api/token_spec.rb
> +    it '正しいログイン情報の場合' do
`正しいログイン情報の場合`はcontextに書く内容かな
itに書くのは期待する動作であって、条件ではないのでそこは注意

例えばここだと
```
context "正しいログイン情報の場合" do
  it "200が返って、アクセストークンを返すこと" do
      expect(response).to be_successful
      expect(response.parsed_body.keys).to include('access_token')
  end
end
```
200のくだりを省略するとか、アクセストークンが入ったjsonを返すことみたいにもっと具体的にitを書いてもいい　そこは自由だと思う

2023-05-08 07:48 UTC, Taku3939 commented
よくみたら色々とおかしかったですね...
修正しました

2023-05-08 11:02 UTC, tk0miya reviewed
本来であればメインコードと spec は一緒の PR にしたいですね。

* spec とメインコードは対の存在なので、合わせて読みたい
* spec の指摘によってメインコードが変化することもある
* CI を使って、spec をパスさせてからマージしたい

2023-05-08 11:02 UTC, tk0miya commented on spec/utils/token_util_spec.rb
> +    payload, header = TokenUtil.decode(access_token)
雑談: もし自分が書くとしたら、email, access_token は let 変数にして、decode メソッドの呼び出しは subject にしますね。
少しやりすぎな気もするので雑談ラベルにしますが、spec を書く際はどこが準備でどこがテスト対象、どこが結果の確認なのかを意識できると良さそうです。

2023-05-09 08:59 UTC, Taku3939 commented on spec/utils/token_util_spec.rb
> +RSpec.describe 'TokenUtil' do
メソッドごとにdescribe分けるようにして、下の3つについてencodeの検証もするように変更しました

-  'トークンが正しくエンコードできる場合'
- 'emailアドレスが空の場合'
- 'emailアドレスの形式が間違っている場合'


https://github.com/sls-training/2023-rails-sample/blob/c3845ebe7ce6d0ee861dcacbf7097e839af46b71/spec/models/access_token_spec.rb#L33-L62

2023-05-09 09:10 UTC, Taku3939 commented on spec/utils/token_util_spec.rb
> +  it '生成したjwtが正しくデコードできることの検証' do
アクセストークンに名称変えて、context等も修正しました。

2023-05-09 09:10 UTC, tk0miya commented on spec/utils/token_util_spec.rb
> +    expect(payload['exp']).to eq (Time.zone.now + 3600).to_i
お、この確認方法なら問題ないですね。

ちなみに、時間を細かくチェックしたい場合はこの記事で紹介されている timecop gem や travel_to を使って時間を固定すると便利です。
https://techracho.bpsinc.jp/penguin10/2023_02_09/67780


たとえば、今回話題になった古いトークンをデコードするときの動きを確認する場合などは、この仕組みが便利です。
※ よく考えると、spec としては例外を投げることを明記しておいたほうがわかりやすい気がしますね

2023-05-09 09:46 UTC, tk0miya commented on app/models/access_token.rb
> +    raise '入力している文字列が空か正しくありません' unless Regexp.new(/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i).match?(email)
ここで形式チェックするのは適切かなあ。

原理原則でいうと、システムに入力されたときにバリデーションを行い、システムの中では検証されたデータを扱うというのがよいとされています。
さて、このメールアドレスのチェックを行うのはこのモジュールが適当でしょうか。

2023-05-09 09:46 UTC, tk0miya commented on spec/models/access_token_spec.rb
> +  end
この位置はこの spec の先頭で、すべての spec に対して適用されます。この位置に書くのは適当でしょうか。
(ほぼグローバル変数と言ってもおかしくない位置です)

たとえば `expired_access_token` は `context 'アクセストークンが期限切れの場合'` でしか使われないものですよね。
関係ないすべての spec で JWT.encode を計算するのは適当でしょうか。

email のような無味乾燥で、全てで使いそうな値であればともかく、それ以外の値は context と対になるように書くのが良いと思います。
感覚としては email についても、もう一段下の describe の中に移動するのがよいですね。
メソッドが増えたときに、すべてのメソッドで email が必要だとも言えないですし。

2023-05-09 09:46 UTC, tk0miya commented on spec/requests/api/token_spec.rb
> +          expect(response).to be_successful
この書き方しらなかった。へー

2023-05-09 09:46 UTC, tk0miya commented on spec/requests/api/token_spec.rb
> +  let(:noadmin) { create(:user, :noadmin) }
上のコメントと同様ですね。ここはファイル内のすべての spec に共通の場所なので、なるべくここに変数を起きたくないです。

また、`context 'ユーザがadminの場合'` とか `context 'ユーザがAdminでない場合'` という表記があるので、近い場所に置きたいですね。
```
context 'ユーザがAdminでない場合' do
  let(:user) { create(:user, :noadmin) }

  ...
end
```

こう書くと context と let が揃っているので気持ちよく見えませんか。

2023-05-09 09:46 UTC, tk0miya commented on spec/requests/api/token_spec.rb
> +  let(:user) { create(:user) }
現在用意している factory だと `create(:user)` で admin ユーザーができるんですね。

このままでも正しい動きをするのですが、 `:admin` trait を用意して
```
let(:user) { create(:user, :admin) }
```
と書けるようにしたほうが宣言的に思えませんか。

2023-05-10 00:23 UTC, Taku3939 commented on app/models/access_token.rb
> +    raise '入力している文字列が空か正しくありません' unless Regexp.new(/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i).match?(email)
このモジュールを使うコントローラでチェックを行えていれば良いですか？
Userのemailにそもそもvalidateがかかっているので、controller側から間違ったemailが入ることはないのでemail検証のテスト自体無くしても良いと思ったのですがどうでしょう？

2023-05-10 00:57 UTC, Taku3939 commented on spec/requests/api/token_spec.rb
> +  let(:user) { create(:user) }
変更したので閉じます

2023-05-10 00:59 UTC, Taku3939 commented on spec/models/access_token_spec.rb
> +  end
context下におくように変更しました

2023-05-10 00:59 UTC, Taku3939 commented on spec/requests/api/token_spec.rb
> +  let(:noadmin) { create(:user, :noadmin) }
上のコメント同様に修正しました

2023-05-10 01:11 UTC, Taku3939 commented on spec/requests/api/token_spec.rb
> +          expect(response.parsed_body.keys).to include('access_token')
変更しましたが、parsed_bodyの方は`{"access_token"=>"eyJhbGciOiJIUzI1NiJ ...`と帰ってくるのでシンボルとして判断できないのですが、どちらが綺麗に見えるでしょうか？

```rb
 expect(response.parsed_body.symbolize_keys).to have_key(:access_token)
```

or

```rb
 expect(response.parsed_body).to have_key('access_token')
```

2023-05-10 01:30 UTC, Taku3939 commented
指摘された箇所修正しました

2023-05-10 01:52 UTC, tim-toga commented on spec/factories/users.rb
> -    admin { true }
traitのadminかnoadminを指定しないとadminがnilになるから、消さない方いいような

```ruby
admin { [true, false].sample }
```
とか

2023-05-10 01:52 UTC, tim-toga commented on spec/models/access_token_spec.rb
> +        expect { subject }.to raise_error(JWT::ExpiredSignature, 'Signature has expired')
AccessToken::Errorとかの専用例外を定義した方がcontroller側で扱いやすいかも

controller側で複数モデルからの例外を扱う時に、`JWT::ExpiredSignature`だと、どのモデルで発生した例外かを見分けたい時とかに不便になる

2023-05-10 01:52 UTC, tim-toga commented on spec/models/access_token_spec.rb
> +        expect { subject }.to raise_error(JWT::ExpiredSignature, 'Signature has expired')
このMRではこのままでいいです。（修正するかはお任せします）

2023-05-10 02:11 UTC, tk0miya commented on spec/requests/api/token_spec.rb
> +          expect(response.parsed_body.keys).to include('access_token')
手癖でシンボルにしてしまったけど、parsed_body が文字列を返すのであれば後者がいいね。
シンボルであることは重要な要素ではないので、symbolize_keys を呼ぶのは意味がないです

2023-05-10 02:12 UTC, tk0miya commented on spec/utils/token_util_spec.rb
> +  it '生成したjwtが正しくデコードできることの検証' do
LGTM!!

2023-05-10 02:22 UTC, tk0miya commented on spec/factories/users.rb
> +    admin { [true, false].sample }
`#sample` を使うのはいいですね。
trait を指定しない場合に「なにかいい感じのユーザー」を作ることができるので、テストがリッチになります。
※ 明示的に admin or noadmin が欲しい場合は trait を指定することになる

雑談: ちなみに差分を見るとわかるのですが admin の行が変わってますね。
差分が小さい方がレビュアーの負担が減るので、なるべく並び替えなどは行わないほうが良いですね。
このくらいの差であればひと目で分かるのですが、規模が大きい/距離が離れていると移動なのか変更を含むのかわかりづらくてレビューの際に漏れが生じやすいです。
(今回は大したことないので、わざわざ戻すほどではないかなーとは思います)

2023-05-10 02:22 UTC, tk0miya commented on spec/models/access_token_spec.rb
> +        expect { subject }.to raise_error(JWT::ExpiredSignature, 'Signature has expired')
複数の種類のトークンを扱うようになったら (!= 複数個のアクセストークンを扱う)、でいいんじゃないかな。
いま進めている API の範囲では、トークンの種類が増えることはないだろうし、カスタム例外を作るのはやりすぎだと思いました。

2023-05-10 02:24 UTC, tim-toga approved these changes

2023-05-10 02:28 UTC, tk0miya commented on app/models/access_token.rb
> +    raise '入力している文字列が空か正しくありません' unless Regexp.new(/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i).match?(email)
>このモジュールを使うコントローラでチェックを行えていれば良いですか？

おおよそ正しいです。
`AccessToken` モデルは渡ってきた email が正しい形式であることを期待するだけにして、形式の担保は呼び出し側に責任をもたせるのが良いと思います。

「おおよそ」とコメントしたのは、今回作るであろう controller では

1. API クライアントから email パラメータが分かってくる
2. email パラメータを元に `User` を検索する
3. 取得した `User` レコードの `email` を元に `AccessToken` オブジェクトを作る

という流れになると思います。
この場合、形式チェックを行わなくても良いのではないか、と考えます。
おかしな形式の文字列が渡ってきた場合、2. のところで検索に失敗するはずですしね。
(もちろん、DB に変なデータが入っていないことが前提ですけどね)

2023-05-10 03:31 UTC, tk0miya commented on spec/utils/token_util_spec.rb
> +RSpec.describe 'TokenUtil' do
>header, payloadの書き方同じ処理をして短調さを感じてしまうこと

ある程度はやむを得ないですね。
spec に複雑なコードを書いてしまうと、spec そのものに不具合が発生してうまくテストしそびれてしまうということもあります。
本当に何回も何回も出てくるパターンについては省力化をしたいところですが、数回程度であれば愚直に書く方が良いとも思います。

>raise_error(RuntimeError, "メッセージ") で 以前の話でメッセージを書く必要はないと考えたのですが良いのか

そのメッセージが重要さによって判断するのが良いです。
メッセージに強い意味があり、このモデルの利用者にとってこのメッセージが重要かどうかがポイントだと思います。

個人的には例外のメッセージそのものは重要ではないと考える (意味をもたせるぐらいなら例外を分ける) ので、重要ではないと考えます。

2023-05-10 03:33 UTC, tk0miya commented on spec/models/access_token_spec.rb
> +        expect(payload[:sub]).to eq email
質問: そもそもの話を聞きそびれていることに気づきました。ここってなんで email を保存するようにしたんでしたっけ。user_id の方が楽じゃない? とかって考えたんですがどうでしょうか。

※ この PR のやりとりはおおよそ収束されてきたので、対応するとしても別の PR でいいかも、とは思ってます。

2023-05-10 03:35 UTC, tk0miya approved these changes
いくつかコメントを残しましたが、基本的に問題なさそうなので +1 します。
追加対応をするにしても、一旦マージした上で別 PR の方がやりやすそうに感じました。

2023-05-10 03:35 UTC, tk0miya commented on spec/models/access_token_spec.rb
> +    context 'アクセストークンが正しくエンコードできる場合' do
email の形式チェックをなくしたことによって、context が分岐しなくなったから、この context は省略可能だね。

2023-05-10 04:10 UTC, Taku3939 commented on spec/models/access_token_spec.rb
> +        expect(payload[:sub]).to eq email
確かにidでいいかもしれないですね。
べつのPRで変更出します

2023-05-10 04:17 UTC, Taku3939 commented
+2ついてるのでmergeします

2023-05-10 04:17 UTC, merged