CIにアプリの起動コマンドを追加
sls-training/2023-rails-sample pull request #66
Opened 2023-06-05 02:20 UTC by Taku3939

## やったこと
自分のサーバーのAPIを呼ぶのでテストを呼ぶ前にバックグランドでサーバーを起動、migrateを行うように変更した

2023-06-05 02:50 UTC, tk0miya requested changes
今回は自分のサーバに対してリクエストするのでこういうアプローチでもよいのですが、自分の管理下にないサーバの場合、こういった対応は難しいです。

ですので、サーバを起動するのではなく、サーバを起動しなくてもテストを実行できるようにするというアプローチを取りたいです。
webmock というキーワードで調べてみてください。

2023-06-05 02:50 UTC, tk0miya commented on .github/workflows/github-action.yml
> +            rails db:migrate RAILS_ENV=development
Rails サーバを起動してからデータベースを初期化するのはなんか変ですね。
本来は逆の関係では?

2023-06-05 06:43 UTC, Taku3939 commented
>今回は自分のサーバに対してリクエストするのでこういうアプローチでもよいのですが、自分の管理下にないサーバの場合、こういった対応は難しいです。

一旦、 こちらのPRでテストを通せる状態で先に他のPRを行って、webmockで書き換えるPRを別で出します

2023-06-05 06:47 UTC, Taku3939 commented on .github/workflows/github-action.yml
> +            rails db:migrate RAILS_ENV=development
コードの順番を変更しました

2023-06-05 07:05 UTC, tk0miya approved these changes

2023-06-07 09:30 UTC, KT-tim approved these changes

2023-06-07 09:30 UTC, merged