トークン生成の関数を実装
sls-training/2023-rails-sample pull request #68
Opened 2023-06-05 02:34 UTC by Taku3939

## やったこと

#65 で作成したメソッドを用いてトークン生成のAPIを呼ぶ関数を作成した

adminのユーザのemail,passwordを用いて実行した場合、access_tokenが返る
それ以外の場合、nilが返る

2023-06-05 07:18 UTC, tk0miya requested changes
今回追加してもらったモデルをどのように使うのか、というイメージを付けるためにも spec がほしいです。
CI が動くようになっているわけですし、今後は spec のないコードはマージするのは NG にしたいです。

2023-06-06 09:13 UTC, tk0miya commented on spec/models/users_api_spec.rb
> +    subject { UsersApi.create_token(email:, password:) }
さて、spec を追加してもらったわけですが、いくつか質問です。

* 今回 `UsersApi` というモデルを作りましたが、今後ユーザーごとに記事(articles)を持てるような API が増えた場合、どのようなモデル/メソッドを用意するとイメージしますか?
* そのときにこの `UserApi.create_token` というメソッドの置き場所は適当でしょうか
* 今回、モデル名に Api という suffix をつけていますが、今後、データベースの場合は UserDb とか UserMySql といった名前にしますか? それとも API の場合だけつけるのでしょうか?

2023-06-06 09:13 UTC, tk0miya commented on spec/models/users_api_spec.rb
> +      contexts.each do |(title, password)|
bikeshed?: rspec 内でループや条件分岐といった構成が出てくるのはちょっとモヤッとしますね。

参考: https://qiita.com/jnchito/items/eb3cfa9f7db752dcb796 (今回のケースとはちょっと違う気もするけど)

2023-06-06 09:29 UTC, tk0miya commented on spec/models/users_api_spec.rb
> +      contexts.each do |(title, password)|
内容がまったく同じの context, it が並んでいると怒られた気がするけど、今回の場合はパスワードが正しい/間違っているという違いがある (let 変数が違うはず) ので、怒られないはずだけどなあ。

2023-06-06 09:33 UTC, Taku3939 commented on spec/models/users_api_spec.rb
> +    subject { UsersApi.create_token(email:, password:) }
> 今回 UsersApi というモデルを作りましたが、今後ユーザーごとに記事(articles)を持てるような API が増えた場合、どのようなモデル/メソッドを用意するとイメージしますか?

Userと同様にArticlesApiを作成し、その中でcreate_articles, delete_articlesなどのメソッドを定義することをイメージします

> そのときにこの UserApi.create_token というメソッドの置き場所は適当でしょうか

確かにトークン生成はUserだけのものではないのでUserApiではなく、TokenApiとかに名前を変えた方が良さそうな気がします

> 今回、モデル名に Api という suffix をつけていますが、今後、データベースの場合は UserDb とか UserMySql といった名前にしますか? それとも API の場合だけつけるのでしょうか?

確かにそう考えるとおかしいですね。
`models/api/token.rb`, `models/api/user.rb`にファイルを移して、
namespaceにAPI、モデル名はそのままToken, Userという形にするのはどうでしょうか？

2023-06-06 09:37 UTC, Taku3939 commented on spec/models/users_api_spec.rb
> +      contexts.each do |(title, password)|
itの内容が同じで怒られてしまったのですが、ちょっと記憶違いかもしれないので次回確認もしてみます

2023-06-06 09:52 UTC, tk0miya commented on spec/models/users_api_spec.rb
> +    subject { UsersApi.create_token(email:, password:) }
いい考えだと思います。
spec を作ることで「用意したモデルがどのように呼び出されるのか」「命名やパラメータの付け方は適当か」といったことがチェックできます。

以前 TDD の話をした記憶がありますが、TDD では最初にテストを書くことで「そのモジュールがどう使われるのか」というのを最初に設計します。

* クラス名はなんという名前か。それは適切か
* メソッド名はどういうものか。それは適切か
* 引数はどういうものか、並び順は、キーワード名はどういうものか。それは適切か
* 機能のバランスは取れているか。責務を分割する必要はないか。

長く使われるプログラムでは、こうした名前のチョイスや機能構成について検討が求められます。
TDD が重要とは言いませんが、コードを書く際はこういった視点をもって設計ができるといいですね。

>models/api/token.rb, models/api/user.rbにファイルを移して、
>namespaceにAPI、モデル名はそのままToken, Userという形にするのはどうでしょうか？

ここについては敢えて回答を書かずに一晩置くことにします。
実際に呼び出し側に経ってコードを眺めてみて、そのクラス名、メソッド名で良いのか考えてみてください。

2023-06-07 01:26 UTC, Taku3939 commented on spec/models/users_api_spec.rb
> +    subject { UsersApi.create_token(email:, password:) }
今回user.rbがあるので直接Userだとわかりにくい気はするのですが、ちょっと他に考えは浮かばなかったです。

2023-06-07 01:34 UTC, Taku3939 commented on spec/models/users_api_spec.rb
> +      contexts.each do |(title, password)|
自分の見間違いだったみたいです。直しました

2023-06-07 10:00 UTC, KT-tim commented on spec/models/users_api_spec.rb
> +    subject { UsersApi.create_token(email:, password:) }
サーバー側アプリのuser.rbがあるから、クライアント側アプリのuser.rbを作るとややこしくなるってことだったら、確かにそうです。面倒だろうし鯖もクライアントも１リポジトリでいいよって言った時にはそこまで考えてませんでした...

感想：TDDできてるのはいいですね

2023-06-07 10:20 UTC, KT-tim commented on spec/models/users_api_spec.rb
> +    subject { UsersApi.create_token(email:, password:) }
本来別のアプリとして作るべきなのは認識していたが、リポジトリを分けるのが面倒なのでメンターの許可を取った上で１個のアプリで実装したという背景が抜けてるかもしれないので共有です cc: @tk0miya 
いい感じに分ける方法があればいいんですが

2023-06-07 11:34 UTC, tk0miya commented on spec/models/users_api_spec.rb
> +    subject { UsersApi.create_token(email:, password:) }
返事が遅れてしまってごめんなさい。

>実際に呼び出し側に経ってコードを眺めてみて、そのクラス名、メソッド名で良いのか考えてみてください。

呼び出し側に立ってコードを眺めてみましたか?

提案してもらった内容はこれですよね。

>models/api/token.rb, models/api/user.rbにファイルを移して、
>namespaceにAPI、モデル名はそのままToken, Userという形にするのはどうでしょうか？

これを踏まえると `API::Token.create_token()`, `API::User.get_users()` というモデル名、メソッド名になるという理解でただしいでしょうか。
そして、このネーミングで良さそうと判断したということであってますか?

検討の上でこの名前を推すのであれば、そのまま進めてしまってください。

※ リポジトリを分けるという話はなんとなく把握していたので問題ないですよ。

2023-06-08 00:45 UTC, Taku3939 commented on spec/models/users_api_spec.rb
> +    subject { UsersApi.create_token(email:, password:) }
`API::Token.create_token()`だとTokenが繰り返しになっていて変ですね...
`API::Token.create`のようにtokenやuserを抜いた方がシンプルで良いと思いました。

利用者としてはUserのモデルがAPIから取ってくるかどうかを考える必要はないので、ActiveRecordの命名と同じようなUser.find_by, whereみたいなメソッドを実装して寄せた方がわかりやすいでしょうか？

2023-06-08 02:56 UTC, tk0miya commented on spec/models/users_api_spec.rb
> +    subject { UsersApi.create_token(email:, password:) }
>API::Token.create_token()だとTokenが繰り返しになっていて変ですね...

同意です。上でもコメントをしましたが、ネーミングの問題は使い方をイメージすることが重要です。
ですから、サンプルコードを書くなり、spec を書くなりしてみてほしいです。

僕のコメントは難しいことをせずに、クラスメイトメソッド名を繋げて書いてみただけですよね。
頭の中でいろいろ考えるよりも、利用側のコードを書いてみることは価値があります。
(上で TDD のコメントをしたとおりですね)

今回はネーミングを起点とした議論ですが、この他にも

* どういう機能を持つのか
* どういう引数を持つのか
* どういう返り値を返すのか

といった部分も検討対象になるはずです。

ですから、

>利用者としてはUserのモデルがAPIから取ってくるかどうかを考える必要はないので、ActiveRecordの命名と同じようなUser.find_by, whereみたいなメソッドを実装して寄せた方がわかりやすいでしょうか？

というのはもう少し掘り下げて検討してほしいです。
`API::Token.create_token()` のように、検討することでよりよい構造を見つけることができるはずです。

※ 直感でいうと問題なさそうに見えます。

2023-06-08 02:58 UTC, tk0miya commented on spec/models/users_api_spec.rb
> +    subject { UsersApi.create_token(email:, password:) }
ところで、この PR はどうしましょうかねえ。
後続の PR が繋がってしまっているので、どう扱うといいかはちょっと検討しないとですね。

* あとで直すつもりで一旦マージしてしまう
* 時間を取って (集まって)、集中的によい形を見つけて PR を更新する (いわゆるモブプロ)
* マージを急がず、このまま進める

このあたり、相談できると良さそうですね。

2023-06-08 04:09 UTC, tk0miya commented on app/models/api/token.rb
> +      def create(email:, password:)
リネームありがとう。

この部分は返り値がちょっと気になりますね。

* ActiveRecord の `User.create` は User オブジェクトが返るが、 `API::Token.create` は Hash が返るのは違和感はない?
* 正常終了の場合と、エラーの場合で属性がことなるが、アプリケーションはどのように見分けるとよいのか


※ 五月雨の指摘になって申し訳ないのだけど、他で会話したように、実際の呼び方を見てみないとわからないことって結構多いのでごめんね

2023-06-08 06:43 UTC, tk0miya commented on app/models/api/access_token.rb
> +    def initialize(email:, password:)
いずれどこかで触れますが、API の呼び出しというのは副作用があるものです。
モデルクラスに見せることで、DB も API も同じインターフェースで扱えるようにすることはできるのですが、まったくおなじ使い方にはできません。

※ controller 側を実装するときに触れるつもりだったのですが、たとえば API の呼び出しに失敗する (接続エラー、タイムアウトなど) ということもあり、response が得られないというケースがあります。


そう考えたときに `Api::AccessToken.new` というのは副作用が少なさそうに見えてしまうので、せっかく考えてもらったものの、このネーミングは避けたいです。
感覚的なものなので説明は難しいのですが `.create` は副作用があっても納得があるけれど、 `.new` は副作用がないことを期待したいという気持ちがあります。

※ さらにいうと、将来拡張が進んでいくと、spec などで `Api::AccessToken` のインスタンスを作りたくなる日が来るので、API の呼び出しなしでインスタンスが作れる `.new` はキープしておきたいという狙いがあります。そうすれば factory_bot などが使えますしね。

2023-06-08 06:47 UTC, tk0miya approved these changes
最後に１つだけ物言いを付けたのですが、その他は問題ないので、フライングで +1 します。
マージしてからリネームでも、リネームしてからマージでも構いません。

長めの議論で大変だったと思うのですが、おつかれさまでしたー。

ちなみに、途中で出てきた `Api::Token.create_token()` というネーミングもそんなに悪くはないと思っていました。
モデル的ではないので `Api::Token` というモジュールの下に、メソッドが生えているという建付けであれば、この構造もそこまで悪くはないと感じます。
※ その場合は app/models よりも app/lib あたりのその他のコンポーネント置き場に置くのが良いと思う

モデルっぽく見せるのと、ライブラリっぽく見せるのの、どちらが良いのかというのは意見が分かれそうではあるのですが、個人的にはモデルっぽく見せたほうがよい (生の JSON を返すと不便なことも多い) という感覚があります。
あとは Rails のモデルと近いほうが馴染みやすいというのもありますね。

2023-06-08 07:33 UTC, KT-tim commented on spec/models/api/access_token_spec.rb
> +RSpec.describe 'AcessToken' do
別に直さなくてもいいけどタイポありますね（described_class使ってたらもしかしたらアウトだったかも）

2023-06-08 07:33 UTC, KT-tim approved these changes

2023-06-08 07:33 UTC, tim-toga approved these changes

2023-06-08 07:33 UTC, tim-toga commented on spec/models/api/access_token_spec.rb
> +  describe '#create' do
* 今回はこれで大丈夫です

このspecはAPIのspecになっているように見えます。このモデルの責務は
* Successが返ってきた場合にvalueに値が入ること
* Success以外の場合はerrorsに値が入ること
のみかなと

2023-06-08 07:40 UTC, Taku3939 commented
+3なのでマージします

2023-06-08 07:40 UTC, merged