指定IDのユーザを返すAPIを作成
sls-training/2023-rails-sample pull request #7
Opened 2023-05-01 07:33 UTC by Taku3939

## やったこと
前回のUsersのAPIの指定 ID のユーザのを返す APIの部分です

2023-05-01 07:40 UTC, tk0miya commented on api/users/show.md
> +<table>
あれ、ここ表形式にしたのって意図的です?
読みやすさが上がるわけでもないし上に書きづらいこともあって、元の形式のままでよいのでは? と考えました。

2023-05-01 07:40 UTC, tk0miya commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
前の PR でコメントしたけど、ユーザーを作った直後だとどうなります?

2023-05-01 07:40 UTC, tk0miya commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
単に趣味の問題ですが、 `created_at`, `updated_at` は最後に持っていきたいですね。

2023-05-01 07:40 UTC, tk0miya commented on api/users/show.md
> +Media type: `application/json`
これでも正しいのだけど、Content-Type: application/json と書いたほうが伝わりやすいかもしれませんね

2023-05-01 07:40 UTC, tk0miya commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
前の PR でコメントした日付の形式の件って大丈夫そうです?

2023-05-01 07:42 UTC, Taku3939 commented on api/users/show.md
> +<table>
githubでpreviewした時可読性いいかなと思ったんですけど、元のままで良さそうなら戻します

2023-05-01 07:44 UTC, Taku3939 commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
アクティブでない時は401で`user not activated`になるようにしたんですけどコメントでも書いた方が良かったですね(書きます)

2023-05-01 07:47 UTC, tk0miya commented on api/users/show.md
> +<table>
このくらいの規模だとあまり変わらないと思う。
API の規模が大きくなると、単なる markdown が厳しいという結論になるので、あまり頑張るところではないと思いました (どういうマークアップするかを頑張って考えても、いずれ使われなくなる)。

ということで、書きやすい構造のほうが良いと思います。

現状だと閉じタグ忘れたり、壊れたりしそうなあたりに嫌な匂いを感じます。

2023-05-01 07:48 UTC, Taku3939 commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
Dateが日付でDateTimeが時刻含めてるってことですよね。大丈夫だと思います

2023-05-01 07:50 UTC, tk0miya commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
ここはふたつのユーザーが出てきますよね。

* アクセストークンを発行した (現在ログインしている) ユーザー
* API 呼び出し時に指定したユーザー

前者がメール認証されていない場合は 401 が返ってくるのは予想が付いたのですが、後者についてはどうでしょうか。

* メール認証済みのユーザーでログインして (トークンを取得して)
* メール認証されていないユーザーの情報を取得する

とした場合に何が起きるのかは API 定義からは読み取れませんでした。
この場合も 401 に私用、という話ですかね?

2023-05-01 07:51 UTC, tk0miya commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
https://github.com/sls-training/2023-rails-sample/pull/1#discussion_r1181370411

このコメントの後者について考慮されてなさそうです。

コメント探すのをサボったので説明が曖昧でしたすみませんw

2023-05-01 07:52 UTC, tk0miya commented on api/users/show.md
> +<table>
背景を説明しておくと、僕は趣味で Markdown マイスター(自称)をやっているので、Markdown の書き方にこだわりがあります。

2023-05-01 07:58 UTC, Taku3939 commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
こちらも確認不足でした(たくさんコメントありすぎてわからなくなってますw)

2023-05-01 08:49 UTC, Taku3939 commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
修正しました

2023-05-01 08:50 UTC, Taku3939 commented on api/users/show.md
> +Media type: `application/json`
修正しました

2023-05-01 08:51 UTC, Taku3939 commented on api/users/show.md
> +<table>
前のフォーマットに戻しました。

2023-05-01 08:55 UTC, Taku3939 commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
コメントの理解ができてませんでした。
メール認証されていないユーザも取得は行えるのでその場合は取得できるようにします。

2023-05-01 09:04 UTC, Taku3939 commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
- メール認証済みでないユーザーではトークン取得できないようにした
https://github.com/sls-training/2023-rails-sample/blob/ffb636f452b696bbc484eefbe830c17344cee622/api/token.md?plain=1#L5-L6

- メール認証済みでないユーザの取得は可能で良いと思ったので余計なコメントを削除

2023-05-01 09:13 UTC, tk0miya commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
確認ありがとう。さて、その上で最初の質問に戻ると、メール認証済みでないユーザーを取得した場合、 `activated_at` には何が入りますか?

2023-05-01 09:15 UTC, tk0miya commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
GitHub のコメントはそれぞれ状態を持っているので、対応が終わったやつは Resolved にして閉じてしまうのがよいです (もしくは中途半端なものは閉じないでおく)。そうすれば対応済みのものは非表示になるので、「表示されているコメントだけ対応すれば良い」という整理になるので、シンプルで済みます。

2023-05-01 09:16 UTC, Taku3939 commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
簡易なものとか自分で直せたか判断できれば自分で閉じても大丈夫ですか？

2023-05-01 09:19 UTC, tk0miya commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
プロトコルを決めるのがよいですね。

* コメントをした人が確認してから閉じる
* 指摘を受けたほうが閉じる
* その他、いい感じに閉じるw

僕は mixed なアプローチで、些細なやつは誰でも閉じられるが、解釈が曖昧そうなやつは本人に委ねるというのがいいと思ってます。

2023-05-01 09:24 UTC, Taku3939 commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
nil(null)ですかね。DateTime | null とかに型書くのはどうでしょうか？

2023-05-01 09:25 UTC, a5ob7r commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
これって「未定義です」と明示するのはアリなんですかね。その場合は未定義なのでユーザはこの値を使うべきではない、といった仕様は(WEB APIではどうかわかりませんが)ありそうな気がします。この場合は、 `datetime | none` になりそうなので、わざわざ未定義にする必要はないかもしれませんが。

2023-05-01 09:26 UTC, Taku3939 commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
未定義にするなら返さないで良さそうかなと個人的には思う

2023-05-01 09:27 UTC, a5ob7r commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
それもそうか。

2023-05-01 09:29 UTC, tk0miya commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
>nil(null)ですかね。DateTime | null と型を書くのはどうでしょうか？

いいと思います！

2023-05-01 09:31 UTC, Taku3939 commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
JSTにしてみます。(ついでにrailsでutcからjstにする方法勉強したいです)
日本の人が利用者の大部分ならJSTの方が良いって思ったんですが、一般的なのはUTCだからそちらを使うべきだったりしますか？

2023-05-01 09:36 UTC, tk0miya commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
>これって「未定義です」と明示するのはアリなんですかね。

起きうる頻度とか可能性次第ですかねえ。
未定義にしたとして、実際にそういう事が起こってしまった場合は、不具合に繋がる可能性があるんですよね。
null を返す場合、クライアントがクラッシュする可能性は大いにありますよね。

あらかじめ null が返ってくるとわかっていれば対処の仕様もあるものの、未定義にした場合は回避策を講じることが出来ないので、それをクライアントに伝えるべきかどうかというところがポイントになってきます。
たとえば TS だったら `datetime` と `datetime | null` は全然違う型なので、あらかじめ教えてほしいやつですよね。

一方で、ほぼ発生しない (数秒で解消するので無視できるとか) であればわざわざ定義しないというのも選択肢に入りそうです。



脱線すると、API クライアントがスマホアプリであった場合は、クライアントの更新に手間がかかることになります。Apple や Google の審査を通す必要があったり、ユーザーに強制アップデートを強制する必要があるとかですね。
未定義にするのはかんたんですが、それが実際に発生するとなると思わぬコストがかかることがあるので、明示するのが良いのか、暗黙にするのがよいのかはちゃんと検討したほうが良いです。
少なくともこのケースについては、明示するのが大変というわけではないのでサボるコストとは見合わない気がします。

2023-05-01 09:40 UTC, Taku3939 commented on api/users/show.md
> +| activated_at | DateTime | メール認証した日       |
(確かにTSでnull許容で書いてなかったらきれるかも...)

2023-05-01 09:46 UTC, tk0miya commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
プロジェクトで方針を決めてしまっていいと思います。
特にこれが優れているというものがあるわけではないです。

個人の好みとしてはこんな感じでしょうか。

* タイムゾーンが明示されていることは必須
    * タイムゾーンなしはありえない (ズレが生じる)
* どのタイムゾーンを選ぶかはおまかせ (プロジェクトの合意を優先する)
* 個人的な好みとしては UTC がよい
    * 時刻の管理 (保存や伝達) と表示は別のものという考えに基づいている
    * データベースへの保存や API のレスポンスでは、中立な値である UTC として保持したい
    * 時刻の表示はユーザーの設定に応じて変化する(可能性がある)ので、表示の際にタイムゾーンを変化させたい
* とはいえ、殆どの仕事では JST で入力、JST で表示されるので、UTC に変化するのは趣味の領域に入っている気もする

2023-05-01 10:12 UTC, KT-tim requested changes

2023-05-01 10:12 UTC, KT-tim commented on api/users/show.md
> +  "activated_at": "Sat, 22 May 2021 14:55:10.214590000 JST +09:00",
時間の表示規格に関しては一般的なiso8601形式を使うのがいいと思います

今のこの形式は実はRubyが適当に作ったやつなので、なんと誰も(Ruby自身も)読めないみたいです
```
[34] pry(main)> Time.parse("Sat, 22 May 2021 14:55:10.214590000 JST +09:00")
=> 2021-05-22 14:55:10.21459 +0000 # 動いてるように見えてタイムゾーンを読めていない
```

2023-05-02 01:20 UTC, Taku3939 commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
ISO8601でタイムゾーンはUTCに変更しました。
[ついでに少し調べたのまとめました。](https://hackmd.timedia.co.jp/r9OR1VAjTbCqj0reszXM3w)

2023-05-02 03:01 UTC, tk0miya approved these changes
いっこ気になったところをコメントしましたが、その他は問題なさそうです。
フライングで +1 します。

2023-05-02 03:01 UTC, tk0miya commented on api/users/show.md
> +トークンがない時は 403<br>
雑談: なんで br 挟んでるんだろ? と思ったのだけど、ローカルで preview すると .md 上の改行が維持されないのか。

GitHub 上のレンダリングと一般的なレンダリングの違いだね。Markdown つらい…

2023-05-02 03:15 UTC, tk0miya commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
まとめた結果にコメントし忘れていた。

* Unixtime 形式
    * 数値の `1460426012` が Unixtime 形式です。
    * この説明だと irb の出力は Unixtime 形式に見えてしまうのでご注意を
    * 他の説明に合わせるなら `Time.now.to_i` するのがいいと思います
* RFC822形式
    * RFC822 はすでに廃止扱いです。現在は RFC5322 が最新です
        * IETF の RFC822 の記事を見ると、サイドバーに Obsoleted by ... というリンクがありますよね
            * https://datatracker.ietf.org/doc/html/rfc822
        * たどっていくと RFC5322 にたどり着きます: https://datatracker.ietf.org/doc/html/rfc5322
    * RFC822 をを覚えておけば、最新版にたどり着けるので、覚えておくなら RFC822 かな
* Time型はどれでもない（多分）
    * Ruby には `#inspect` というメソッドがあり、各オブジェクトを「人間が読める形式」に変換します
    * https://docs.ruby-lang.org/ja/latest/method/Object/i/inspect.html
    * irb は返り値の `#inspect` を呼び出して、それを実行結果として表示しています
* in_time_zoneで変換するとRFCになってる
    * よく見比べてみてください。RFC822 とは形式が違いますよね。
    * タイムゾーンが含まれています。
    * これは単に `ActiveSupport::TimeWithZone#inspect` が RFC822 とよく似た形式で文字列化しているのです
        * `Time#inspect` とも違うので、 `Time.now` と結果が違うのはそのため
* Time.currentはrails only
    * だいたいあってる
    * 厳密に言うと Rails に含まれる ActiveSupport というライブラリに由来しています
    * そのため、Rails を使わずに ActiveSupport だけ使うということもできます
* 特に理由がなければiso8601を使えばいい
    * 結論はあっているけどひとつ飛ばしな印象です
    * ISO8601 形式はデータ交換に有利な形式であるから、というのが理由ですね。 
    * 適材適所というように、他に理由があるのであれば ISO8601 を使う必要はありません
        * たとえば、人間に読ませるのが狙いであれば ISO8601 は適当ではないですよね

2023-05-02 04:22 UTC, Taku3939 commented on api/users/show.md
> +| updated_at   | DateTime | 更新日                 |
詳しいコメントありがとうございます...！

2023-05-02 04:26 UTC, KT-tim approved these changes
👍

2023-05-02 04:27 UTC, Taku3939 commented
🙏

2023-05-02 04:28 UTC, merged